{% set name = "icalendar" %}
{% set version = "6.0.0" %}
{% set sha256 = "7ddf60d343f3c1f716de9b62f6e80ffd95d03cab62464894a0539feab7b5c76e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - hatchling
    - hatch-vcs

  run:
    - python >=3.6
    - python-dateutil
    - tzdata

test:
  imports:
    - icalendar

about:
  home: https://github.com/collective/icalendar
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: iCalendar parser/generator
  description: |
    The icalendar package is a parser/generator of iCalendar files for use with
    Python.
  doc_url: http://icalendar.readthedocs.io/en/latest/
  dev_url: https://github.com/collective/icalendar

extra:
  recipe-maintainers:
    - stuertz
