{% set name = "icalendar" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/icalendar-{{ version }}.tar.gz
  sha256: 2c44355a8f006de5ae73fa3f022a1cbe2a0de6b1607ce8879739eb887c4f3471

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - hatchling
    - hatch-vcs

  run:
    - python >={{ python_min }}
    - python-dateutil
    - python-tzdata

test:
  imports:
    - icalendar
  commands:
    - pip check
    - icalendar --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/collective/icalendar
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: iCalendar parser/generator
  description: |
    The icalendar package is a parser/generator of iCalendar files for use with
    Python.
  doc_url: http://icalendar.readthedocs.io/en/latest/
  dev_url: https://github.com/collective/icalendar

extra:
  recipe-maintainers:
    - stuertz
