{% set name = "icalendar" %}
{% set version = "4.0.7" %}
{% set sha256 = "0fc18d87f66e0b5da84fa731389496cfe18e4c21304e8f6713556b2e8724a7a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - python-dateutil
    - pytz

test:
  imports:
    - icalendar

about:
  home: https://github.com/collective/icalendar
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: iCalendar parser/generator
  description: |
    The icalendar package is a parser/generator of iCalendar files for use with
    Python.
  doc_url: http://icalendar.readthedocs.io/en/latest/
  dev_url: https://github.com/collective/icalendar

extra:
  recipe-maintainers:
    - stuertz
